Update the theme
jakartaee/jekyll-theme-jakarta-ee pull request #25
Opened 2022-11-15 14:37 UTC by ericpoirier

Fixes #24 

Signed-off-by: Eric Poirier <eric.poirier@eclipse-foundation.org>

2022-11-15 14:39 UTC, ericpoirier commented
To review: @chrisguindon @autumnfound @ZacharySabourin @oliviergoulet5 
(can't seem to add reviewers in the sidebar)

2022-11-15 15:58 UTC, oliviergoulet5 requested changes

2022-11-15 15:58 UTC, oliviergoulet5 commented on _includes/footer.html
> +      <section class="col-sm-5th padding-top-20" id="footer-eclipse-foundation">
I keep noticing `col-sm-5th` in multiple places. Is this class defined anywhere in the CSS or is it a typo?

2022-11-15 15:58 UTC, oliviergoulet5 commented on _includes/footer.html
> +      <section class="col-sm-5th padding-top-20" id="footer-legal">
`col-sm-5th` is here

2022-11-15 15:58 UTC, oliviergoulet5 commented on _includes/footer.html
> +      <section class="col-sm-5th padding-top-20" id="footer-useful-links">
col-sm-5th is here

2022-11-15 15:58 UTC, oliviergoulet5 commented on _includes/footer.html
> +      <section class="col-sm-5th padding-top-20" id="footer-other">
col-sm-5th is here

2022-11-15 15:58 UTC, oliviergoulet5 commented on _includes/footer.html
> +      <section class="col-sm-5th footer-section-socials" id="footer-socials">
col-sm-5th is here

2022-11-15 16:02 UTC, chrisguindon requested changes

2022-11-15 16:02 UTC, chrisguindon commented on .gitignore
> -.sass-cache
I don't think you should remove this rule.

2022-11-15 16:02 UTC, chrisguindon commented on README.md
> -![Screenshot](https://raw.githubusercontent.com/jakartaee/jekyll-theme-jakarta-ee/master/screenshot.png)
Let's update the screenshot instead of removing it.

2022-11-15 16:02 UTC, chrisguindon commented on assets/css/style.scss
> -@import 'jekyll-theme-jakarta-ee';
I think we should keep these styles. Removing this CSS is outside of the scope of this issue and it should be discussed separately.

2022-11-15 16:02 UTC, chrisguindon commented on assets/css/styles.css
> +.featured-jumbotron h1 {
Let's continue to use sass.

2022-11-15 16:02 UTC, chrisguindon commented on jekyll-theme-jakarta-ee.gemspec
> +  spec.files         = `git ls-files -z`.split("\x0").select { |f| f.match(%r!^(assets|_layouts|_includes|LICENSE|README)!i) }
Let's continue to us sass.

2022-11-15 18:15 UTC, ericpoirier commented on _includes/footer.html
> +      <section class="col-sm-5th padding-top-20" id="footer-eclipse-foundation">
This is a class that we created a while ago so we can have a grid with 5 columns and this is how we decided to name the class.

2022-11-15 18:27 UTC, ericpoirier commented
@chrisguindon I added the sass files back and I updated the screenshot.

2022-11-17 13:03 UTC, chrisguindon commented on _includes/nav.html
> +    <li><a href="/community/">Overview</a> </li>
Links like these needs to be absolute since this theme will be used on a bunch of different domains.

2022-11-17 13:04 UTC, chrisguindon commented on _includes/nav.html
> +    <li><a href="/resources#documentation">Documentation</a> </li>
Same, here. I won't post this comment on every instance but make sure to include the full URL for these type of links.

2022-11-17 13:06 UTC, chrisguindon commented on _includes/footer.html
> +          <li><a href="/compatibility/">Marketplace</a></li>
This does not look right to me. Why is a link to /compatibility has the text Marketplace

I think this is also a bug on the main site.

2022-11-29 14:58 UTC, chrisguindon approved these changes

2022-11-29 15:03 UTC, oliviergoulet5 approved these changes

2022-12-05 14:13 UTC, chrisguindon commented
@jgallimore Any issues with these changes? We would like to merge this work this week!

2022-12-12 13:39 UTC, merged